files:
  # define files included in the analysis (defaults to ["{app,lib}/**/*.rb"])
  included:
    - lib/felflame.rb
    - lib/felflame/component_manager.rb
    - lib/felflame/entity_manager.rb
    - lib/felflame/system_manager.rb
    - lib/felflame/scene_manager.rb
    - lib/felflame/stage_manager.rb
  # define files excluded from the analysis (defaults to [])
  excluded:
